ALTER TABLE media_item ADD COLUMN user_id BIGINT;
ALTER TABLE list ADD COLUMN user_id BIGINT;
ALTER TABLE sync_state ADD COLUMN user_id BIGINT;
ALTER TABLE sync_outbox ADD COLUMN user_id BIGINT;

ALTER TABLE sync_state ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

CREATE INDEX idx_media_item_user_id ON media_item(user_id);
CREATE INDEX idx_media_item_user_deleted ON media_item(user_id, deleted_at);
CREATE INDEX idx_list_user_id ON list(user_id);
CREATE INDEX idx_sync_state_user_id ON sync_state(user_id);
CREATE INDEX idx_sync_outbox_user_id ON sync_outbox(user_id);

ALTER TABLE media_item
  ADD CONSTRAINT fk_media_item_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE;

ALTER TABLE list
  ADD CONSTRAINT fk_list_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE;

ALTER TABLE sync_state
  ADD CONSTRAINT fk_sync_state_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE;

ALTER TABLE sync_outbox
  ADD CONSTRAINT fk_sync_outbox_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE;
